@include('admin.templates.head')
@include('admin.templates.header')
@include('admin.templates.aside')
@yield('body')
@include('admin.templates.footer')
@include('admin.templates.right-side')
@include('admin.templates.script')
